spring.application.name=reddit-clone-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/reddit_clone
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=ThisIsASecretKeyForJwtAuthentication123456
jwt.expiration=86400000